### ISSUE TITLE
pathspec 'release/5.0.4' did not match any file(s) known to git

### ISSUE THREAD

**Issue by pdehaan** [mozilla/create-shield-study#3]
Spotted while creating a new shield study then running <kbd>$ npm install</kbd> on the new template files. Behold:

```sh
$ git rev-parse --short HEAD # ecf131b

$ ./create-shield-study peter-is-no-bueno
? Shield (or Pioneer) shield
? inform Strategy and Insights about your project Yes
? choose all starting libraries shield-study-addon-utils
[FAILED] addMany Missing helper: "fill"
[FAILED] info Aborted due to previous action failure

$ cd peter-is-no-bueno/shield-study

$ npm install

Unhandled rejection Error: Command failed: /usr/local/bin/git checkout release/5.0.4
error: pathspec 'release/5.0.4' did not match any file(s) known to git

    at ChildProcess.exithandler (child_process.js:276:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)

...

added 1716 packages from 2058 contributors and audited 11075 packages in 39.178s
found 11 vulnerabilities (5 low, 5 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

The "release/5.0.4" looks very suspicious, but aligns with the shield-studies-addon-utils" version number in the template package.json:

```json
  "dependencies": {
    "shield-studies-addon-utils": "github:mozilla/shield-studies-addon-utils#release/5.0.4"
  },
```

**Comment by pdehaan** [comment]
Interesting... Per https://github.com/mozilla/shield-studies-addon-utils/branches, I can't see a "release/5.0.x" branch, so maybe somebody deleted it, which is why I'm getting that error.

We should possibly come up w/ rules around deleting branches/tags/releases, since it's possible we break some shield studies when people are relying on specific branch names. Or else maybe we stick w/ using npm for versioning and hosting releases.

**Comment by pdehaan** [comment]
Ref: https://github.com/mozilla/shield-studies-addon-utils/issues/268
